<?xml version="1.0" encoding="utf-8" ?>

<!DOCTYPE class-list[

<!ELEMENT class-list ( filter-list, runner-list, task-list, user-process ) >

<!ELEMENT filter-list (filter*) >
<!ELEMENT filter (para*, attr*) >
<!ATTLIST filter name CDATA #REQUIRED >
<!ATTLIST filter javaClass CDATA #REQUIRED >
<!ATTLIST filter attr (or|and) #IMPLIED >
<!ATTLIST filter enable (true|false) #IMPLIED >

<!ELEMENT attr EMPTY >
<!ATTLIST attr name CDATA #REQUIRED >
<!ATTLIST attr result CDATA #IMPLIED >
<!ATTLIST attr contains CDATA #IMPLIED >
<!ATTLIST attr endsWith CDATA #IMPLIED >
<!ATTLIST attr equals CDATA #IMPLIED >
<!ATTLIST attr equalsIgnoreCase CDATA #IMPLIED >
<!ATTLIST attr matches CDATA #IMPLIED >
<!ATTLIST attr startsWith CDATA #IMPLIED >

<!ELEMENT runner_list (runner*) >
<!ELEMENT runner (para*) >
<!ATTLIST runner owner CDATA #REQUIRED >
<!ATTLIST runner javaClass CDATA #REQUIRED >

<!ELEMENT task (para*) >
<!ATTLIST task owner CDATA #REQUIRED >
<!ATTLIST task javaClass CDATA #REQUIRED >
<!ATTLIST task name CDATA #REQUIRED >
<!ATTLIST task schedule CDATA #REQUIRED >
<!ATTLIST task runInit (true|false) #IMPLIED >

<!ELEMENT user-process ( process* ) >
<!ATTLIST process name CDATA #REQUIRED >
<!ATTLIST process javaClass CDATA #REQUIRED >

<!ELEMENT para EMPTY >
<!ATTLIST para name CDATA #REQUIRED >
<!ATTLIST para value CDATA #IMPLIED>
<!ATTLIST para os CDATA #IMPLIED >
<!ATTLIST para descr CDATA #IMPLIED>

]>

<class-list>

	<!--
		#########################################################################
		# F I L T E R
		#########################################################################
	-->

	<filter-list>

		<!--
			*********************************************************************
			* config filter
			*********************************************************************
		-->

		<!-- system -->
		<filter name="ConfigFilterSystem" javaClass="com.daims.dfc.filter.config.std.ConfigFilterSystem" />
		<!-- interface -->
		<filter name="ConfigFilterInterface" javaClass="com.daims.dfc.filter.config.std.ConfigFilterInterface" />
		<!-- model attribute -->
		<filter name="ConfigFilterModelFieldOid" javaClass="com.daims.dfc.filter.config.model.ConfigFilterModelFieldOid" />
		<!-- entity mib -->
		<filter name="ConfigFilterEntPhysical" javaClass="com.daims.dfc.filter.config.std.ConfigFilterEntPhysical" />
		<!-- host resource mib -->
		<filter name="ConfigFilterHostResource" javaClass="com.daims.dfc.filter.config.std.ConfigFilterHostResource" />
		<filter name="ConfigFilterHostSwRun" javaClass="com.daims.dfc.filter.config.std.ConfigFilterHostSwRun" />
		<!-- bridge mib -->
		<filter name="ConfigFilterBridge" javaClass="com.daims.dfc.filter.config.std.ConfigFilterBridge" />
		<!-- vlan -->
		<filter name="ConfigFilterCiscoVLan" javaClass="com.daims.dfc.filter.config.cisco.ConfigFilterCiscoVLan" />
		<!-- database -->
		<filter name="ConfigFilterDatabase" javaClass="com.daims.dfc.filter.config.std.ConfigFilterDatabase">
			<attr name="categoryName" contains="DB" />
			<attr name="categoryName" contains="DATABASE" />
			<attr name="categoryName" contains="데이터베이스" />
		</filter>
		<!-- tcp mib -->
		<filter name="DagConfigFilter" javaClass="com.daims.dfc.filter.config.std.ConfigFilterTcpMib" attr="and">
			<attr name="dagString" contains="dag=N" />
			<attr name="snmpString" contains="snmp=Y" />
		</filter>
		<!-- L4 session -->
		<filter name="l4.AlteonConfigFilter" javaClass="com.daims.dfc.filter.config.l4.AlteonConfigFilter" />
		<filter name="l4.F5ConfigFilter" javaClass="com.daims.dfc.filter.config.l4.F5ConfigFilter" />



		<!--
			<filter name="BridgeConfigFilter3Com" javaClass="com.daims.test.filter.BridgeConfigFilter3Com">
			</filter>

			<filter name="CdpTestConfigFilter" javaClass="com.daims.test.filter.CdpTestConfigFilter">
			</filter>

			<filter name="ConfigFilterAlcatelAp" javaClass="com.daims.dfc.filter.config.alcatel.ConfigFilterAlcatelAp">
			<attr name="sysObjectId" startsWith=".1.3.6.1.4.1.14823." />
			</filter>

			<filter name="ConfigFilterAlcatelMem" javaClass="com.daims.dfc.filter.config.alcatel.ConfigFilterAlcatelMem">
			<attr name="sysObjectId" startsWith=".1.3.6.1.4.1.800." />
			</filter>

			<filter name="ConfigFilterApcUps" javaClass="com.daims.dfc.filter.config.apc.ConfigFilterApcUps">
			<attr name="sysObjectId" startsWith=".1.3.6.1.4.1.318." />
			</filter>



			<filter name="ConfigFilterCiscoCdp" javaClass="com.daims.dfc.filter.config.cisco.ConfigFilterCiscoCdp">
			<attr name="sysObjectId" startsWith=".1.3.6.1.4.1.9." />
			</filter>

			<filter name="ConfigFilterCiscoMem" javaClass="com.daims.dfc.filter.config.cisco.ConfigFilterCiscoMem">
			<attr name="sysObjectId" startsWith=".1.3.6.1.4.1.9." />
			</filter>

			<filter name="ConfigFilterCiscoModule" javaClass="com.daims.dfc.filter.config.cisco.ConfigFilterCiscoModule">
			<attr name="sysObjectId" startsWith=".1.3.6.1.4.1.9." />
			</filter>

			<filter name="ConfigFilterCiscoTemperature" javaClass="com.daims.dfc.filter.config.cisco.ConfigFilterCiscoTemperature">
			<attr name="sysObjectId" startsWith=".1.3.6.1.4.1.9." />
			</filter>

			<filter name="ConfigFilterCiscoTunnel" javaClass="com.daims.dfc.filter.config.cisco.ConfigFilterCiscoTunnel">
			<attr name="sysObjectId" startsWith=".1.3.6.1.4.1.9." />
			</filter>



			<filter name="ConfigFilterCompaqCpu" javaClass="com.daims.dfc.filter.config.compaq.ConfigFilterCompaqCpu">
			<attr name="sysObjectId" startsWith=".1.3.6.1.4.1.232." />
			</filter>




			<filter name="ConfigFilterExtream" javaClass="com.daims.dfc.filter.config.extream.ConfigFilterExtream">
			<attr name="sysObjectId" startsWith=".1.3.6.1.4.1.1916." />
			</filter>

			<filter name="ConfigFilterHpFs" javaClass="com.daims.dfc.filter.config.hp.ConfigFilterHpFs">
			<attr name="sysObjectId" startsWith=".1.3.6.1.4.1.11." />
			</filter>

			<filter name="ConfigFilterHpProcess" javaClass="com.daims.dfc.filter.config.hp.ConfigFilterHpProcess">
			<attr name="sysObjectId" startsWith=".1.3.6.1.4.1.11." />
			</filter>


			<filter name="ConfigFilterIntigateQos" javaClass="com.daims.dfc.filter.config.intigate.ConfigFilterIntigateQos">
			<attr name="sysObjectId" startsWith=".1.3.6.1.4.1.15589." />
			</filter>

			<filter name="ConfigFilterModel" javaClass="com.daims.dfc.filter.config.model.ConfigFilterModel">
			</filter>

			<filter name="ConfigFilterNableIpt" javaClass="com.daims.dfc.filter.config.nable.ConfigFilterNableIpt">
			<attr name="sysObjectId" startsWith=".1.3.6.1.4.1.25256." />
			</filter>

			<filter name="ConfigFilterNetappNas" javaClass="com.daims.dfc.filter.config.netapp.ConfigFilterNetappNas">
			<attr name="sysObjectId" startsWith=".1.3.6.1.4.1.789." />
			</filter>

			<filter name="ConfigFilterNetbotzFms" javaClass="com.daims.dfc.filter.config.netbotz.ConfigFilterNetbotzFms">
			</filter>

			<filter name="ConfigFilterProbeVer" javaClass="com.daims.dfc.filter.config.std.ConfigFilterProbeVer">
			</filter>


			<filter name="ConfigFilterUcdMemFs" javaClass="com.daims.dfc.filter.config.ucd.ConfigFilterUcdMemFs">
			<attr name="sysObjectId" startsWith=".1.3.6.1.4.1.2021." />
			</filter>

			<filter name="ConfigFilterUnicnIpt" javaClass="com.daims.dfc.filter.config.unicn.ConfigFilterUnicnIpt">
			</filter>

			<filter name="MoTestConfigFilter" javaClass="com.daims.test.filter.MoTestConfigFilter">
			</filter>

		-->

		<!--
			*********************************************************************
			* node filter
			*********************************************************************
		-->
		<!-- set version using sysDescr -->
		<filter name="FilterPreSetVersion" javaClass="com.daims.dfc.filter.node.NodeFilterSetVersion" />
		<!-- set windows version using sysDescr -->
		<filter name="NodeFilterWindowVer" javaClass="com.daims.dfc.filter.node.NodeFilterWindowVer" />

		<!--
			*********************************************************************
			* trap filter
			*********************************************************************
		-->
		<filter name="FilterTrapPrint" javaClass="com.daims.dfc.service.trap.filter.FilterTrapPrint" />
		<filter name="FilterTrapInterface" javaClass="com.daims.dfc.service.trap.filter.FilterTrapInterface" />
		<filter name="FilterTrapThreshold" javaClass="com.daims.dfc.service.trap.filter.FilterTrapThreshold" />
		<filter name="ThrTrapFilter" javaClass="com.daims.dfc.service.trap.filter.ThrTrapFilter" />
		<filter name="FilterTrapLogging" javaClass="com.daims.dfc.service.trap.filter.FilterTrapLogging" />

		<!--
			*********************************************************************
			* syslog filter
			*********************************************************************
		-->
		<filter name="PRINT" javaClass="com.daims.dfc.service.syslog.filter.FilterSyslogPrint" />
		<filter name="FilterSyslogThreshold" javaClass="com.daims.dfc.service.syslog.filter.FilterSyslogThreshold" />
		<!-- 등록되지 않은 장비로부터 SYSLOG 발생할 때 이벤트 발생 -->
		<filter name="FilterSyslogUnkown" javaClass="com.daims.dfc.service.syslog.filter.FilterSyslogUnkown" />

		<!--
			*********************************************************************
			* snmp filter
			*********************************************************************
		-->
		<filter name="NODE" javaClass="com.daims.dfc.service.snmp.filter.UptimeSnmpF">
		</filter>
		<filter name="NODE" javaClass="com.daims.dfc.module.mf.MfSnmpF">
		</filter>
		<filter name="INTERFACE" javaClass="com.daims.dfc.service.snmp.filter.IfSnmpF">
		</filter>
		<filter name="TUNNEL" javaClass="com.daims.dfc.service.snmp.filter.TunnelSnmpF">
		</filter>
		<filter name="VPN" javaClass="com.daims.dfc.service.snmp.filter.VpnPingSnmpF">
		</filter>
		<filter name="PROCESS" javaClass="com.daims.dfc.service.snmp.filter.ProcessSnmpF">
		</filter>

		<!--
			*********************************************************************
			* ping filter
			*********************************************************************
		-->
		<filter name="FPing" javaClass="com.daims.dfc.service.ping.filter.FpingPingFilter">
			<para name="COMMAND_FPING" value="./fping.exe" os="windows" />
			<para name="COMMAND_FPING" value="./fping -c 2" os="unix" />
			<para name="COMMAND_FPING" value="./fping -c 2" os="linux" />
			<para name="NODE_SIZE_IN_THREAD" value="10" descr="fping 수행시 한번에 적용된 노드수" />
			<para name="MO_CLASS" value="NODE,INTERFACE,IP,IPPHONE" descr="적용대상 MO_CLASS" />
			<para name="RETRY" value="3" descr="off인 경우 재 시도 횟수" />
		</filter>
		<filter name="MTR" javaClass="com.daims.dfc.service.ping.filter.MtrPingFilter">
			<para name="MO_CLASS" value="MTR" />
			<para name="COMMAND_MTR" value="mtr -r -n  -c 3" />
		</filter>
		<filter name="URL" javaClass="com.daims.dfc.service.ping.filter.UrlPingFilter">
			<para name="MO_CLASS" value="URL" />
		</filter>
		<filter name="SOCKETPORT" javaClass="com.daims.dfc.service.ping.filter.SocketPingFilter">
			<para name="MO_CLASS" value="SOCKETPORT" />
		</filter>


		<!--
			*********************************************************************
			* traffic filter
			*********************************************************************
		-->
		<filter name="INTERFACE" javaClass="com.daims.dfc.service.traffic.filter.TrafficFilterInterface">
		</filter>
		<filter name="TUNNEL" javaClass="com.daims.dfc.service.traffic.filter.TrafficFilterTunnel" enable="false">
		</filter>

	</filter-list>

	<!--
		#########################################################################
		# R U N N E R
		#########################################################################
	-->

	<runner-list>
		<runner owner="ApService" javaClass="com.daims.dfc.thread.PollingChecker" />
		<runner owner="NbService" javaClass="com.daims.dfc.service.nb.UiBroadcaster" />
		<runner owner="NbService" javaClass="com.daims.dfc.service.nb.NotiBroker" />

		<runner owner="MgrService" javaClass="subkjh.service.services.mgr.HaRunner" />

		<!-- 트래픽 급감을 확인하는 스레드 -->
		<runner owner="AaService" javaClass="com.daims.dfc.service.aa.runner.TrfChecker" >
			<para name="MIN_VALUE" value="1000000" />			
			<para name="SNMP" value="true" />			
			<para name="FLOW" value="false" />			
		</runner>

	</runner-list>

	<!--
		#########################################################################
		# T A S K
		#########################################################################
	-->

	<task-list>
		<!--
			DAgent에서 이 기능을 수행함 ( since 2016.01.19 )
			<task name="TaskDiskCheck" schedule="* * * * *" javaClass="com.daims.dfc.task.TaskDiskCheck" owner="MgrService" />
			<task name="TaskDbCheck" schedule="0,5,10,15,20,25,30,35,40,45,50,55 * * * *" javaClass="com.daims.dfc.task.TaskDbCheck"
			owner="ApService">
			<para name="DATABASE" value="NPRISM_COMMON_ADMIN" />
			</task>
		-->
	</task-list>

	<!--
		#########################################################################
		# U S E R - P R O C E S S
		#########################################################################
	-->

	<user-process>

		<process name="remakeTraffic" javaClass="com.daims.dfc.service.traffic.proc.RemakeTraffic" />

		<process name="agentResourceSet" javaClass="com.daims.dfc.service.dagent.proc.ResourceManage" />

	</user-process>

</class-list>